### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by vladoATL** [martinfekete10/eph-export-woocommerce#1]
Neviem, ako sa mam s vami inak spojit, tak pouzvam tut cestu. 
My pouzivame WC na stranke ochranakorona.sk a zasielame balicky DPD. Je mozne aby ste pridali export do XML alebo csv v tomto fomrate? Alebo mozem to urobit do vasho kodu ja? Kontaktujte ma cez stranku ochranakorona.sk.

<?xml version="1.0" encoding="utf8"?>
<Import>
 <Orders>
 <Order>
 <customer_name>Janko Hraško</customer_name>
 <customer_street>Hlavná 33</customer_street>
 <customer_zipcode>90055</customer_zipcode>
 <customer_city>Lozorno</customer_city>
 <customer_country_id>703</customer_country_id>
 <customer_phone>+421900000000</customer_phone>
 <customer_email>janko@email.com</customer_email>
 <customer_note>Poznamka</customer_note>
 <customer_reference>19052</customer_reference>
 <customer_type>B</customer_type>
 <parcel_type>D</parcel_type>
 <parcel_weight>1</parcel_weight>
 <parcel_volume>090010020</parcel_volume>
 <parcel_order_number>201135654-2</parcel_order_number>
 <sms_preadvice>Y</sms_preadvice>
 <phone_number>+421900000000</phone_number>
 <parcel_COD>Y</parcel_COD>
 <parcel_COD_amount>99.99</parcel_COD_amount>
 <parcel_COD_variable_symbol>123456789</parcel_COD_variable_symbol>
 <parcel_COD_currency>EUR</parcel_COD_currency>
 <parcel_COD_cardpay>Y</parcel_COD_cardpay>
 </Order>
 <Order>
 <customer_name>Jožko Púik</customer_name>
 <customer_street>Hlavná 11</customer_street>
 <customer_zipcode>90101</customer_zipcode>
 <customer_city>Malacky</customer_city>
 <customer_country_id>703</customer_country_id>
 <customer_phone>+421900000001</customer_phone>
 <customer_email>jozko@email.com</customer_email>
 <customer_note>Poznamka</customer_note>
 <customer_reference>19053</customer_reference>
 <customer_type>B</customer_type>
 <parcel_type>D</parcel_type>
 <parcel_weight>1</parcel_weight>
 <parcel_volume>090050020</parcel_volume>
 <parcel_order_number>874785654-2</parcel_order_number>
 <sms_preadvice>Y</sms_preadvice>
 <phone_number>+421900000001</phone_number>
 <parcel_COD>Y</parcel_COD>
 <parcel_COD_amount>119.99</parcel_COD_amount>
 <parcel_COD_variable_symbol>123456999</parcel_COD_variable_symbol>
 <parcel_COD_currency>EUR</parcel_COD_currency>
 <parcel_COD_cardpay>Y</parcel_COD_cardpay>
 </Order>
 </Orders>
</Import>

A jeho verzia v CSV:
customer_name;customer_street;customer_zipcode;customer_city;customer_coun
try_id;customer_phone;customer_email;customer_note;customer_reference;cust
omer_type;parcel_type;parcel_weight;parcel_volume;parcel_order_number;sms_
preadvice;phone_number;parcel_COD;parcel_COD_amount;parcel_COD_variable_sy
mbol;parcel_COD_currency;parcel_COD_cardpay
Janko Hraško;Hlavná
33;90055;Lozorno;703;+421900000000;janko@email.com;Poznamka;19052;B;D;1;09
0010020;201135654-2;Y;+421900000000;Y;99.99;123456789;EUR;Y
Jožko Púik;Hlavná
11;90101;Malacky;703;+421900000001;jozko@email.com;Poznamka;19053;B;D;1;09
0050020;874785654-2;Y;+421900000001;Y;119.99;123456999;EUR;Y

**Comment by martinfekete10** [comment]
Nemal by to byť problém dorobiť, dnes a zajtra mám čas sa tomu povenovať. Keď sa mi to podarí spojazdniť, napíšem email a môžme to odtestovať.
