### ISSUE TITLE
EPH - export hodnoty 'weight' z objednavky do eph xml

### ISSUE THREAD

**Issue by drtikosti** [martinfekete10/eph-export-woocommerce#2]
Zdravim Martin, 
a dakujem za uzitocny modul!!  Mal by som 2 otazky/prosby:

1. EPH nedavno spustilo moznost dopredu uhradit postovne pri podaji cez EPH, k tomu je ale potrebne zadat aj hodnotu vahy zasielky. Produkty vo WC mozu mat vahu zadefinovanu s sekcii shipping a predpokladam ze na urovni objednavky sa tato hodnota tiez deklaruje ako suma vsetkych produktov.
Bolo by mozne tuto hodnotu vaha taktiez zahrnut do exportu?

2. V pripade dobierky zvyknem taktiez do EPH zadavat VAriabilny symbol = cislo objednavky z woocommerce. Bolo by mozne tento udaj v exporte zahrnut taktiez, aby to bolo v udajoch dobieky pridane ako variabilny symbol?

Velka vdaka dopredu.
Matus

**Comment by martinfekete10** [comment]
Zdravím, myslím, že nie je problém tieto veci dorobiť. Kontaktujte ma prosím na martinfekete10@gmail.com, pošlem vám upravenú verziu a keď bude fungovať ako má, updatnem aj verziu tu na GitHube.

**Comment by drtikosti** [comment]
Issue solved, many thanks to Martin!
