### ISSUE TITLE
Dodacia adresa

### ISSUE THREAD

**Issue by udemky** [martinfekete10/eph-export-woocommerce#3]
Zdravim,

akurat som testoval plugin, je super :) Nasiel som tam maly bug, ked je ina dodacia adresa ako fakturacna tak do exportu dava stale fakturacnu. Da sa to fixnut?
A.

**Comment by martinfekete10** [comment]
Zdravím, práve som aktualizoval plugin a táto chyba by už mala byť opravená :) Tiež som pridal okrem doporučeného listu aj export XML pre expres kuriéra a klasický balík.
