### ISSUE TITLE
export pre expres kuriér

### ISSUE THREAD

**Issue by nikolznasik** [martinfekete10/eph-export-woocommerce#4]
Zdravím, plugin je super, chcem sa opýtať či nie je v pláne pridanie aj pre zásielky zasielané ako expres kuriér. Totižto po uploade hárku na stránku pošty nie je toto možné zmeniť a tým pádom je žiaľbohu nepoužiteľný, hoc je fakt super, lebo hárky sú v sekunde hotové a netreba nič prepisovať.

Vďaka za info

**Comment by martinfekete10** [comment]
Zdravím, práve som aktualizoval plugin a pridal som možnosť exportovať XML vo formáte ako pre expres kuriéra, tak aj ako klasický balík :)
